[tool.bumpver]
current_version = "2021.1000.4"
version_pattern = "YYYY.BUILD.UU"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = false
push = false

[tool.bumpver.file_patterns]
"README.md" = [
    "version: {version}",
]
"src/templates/__init__.py" = [
    '__version__ = "{version}"',
]


[tool.towncrier]
package = "templates"
package_dir = "src"
filename = "CHANGELOG.rst"
title_format = "{name} {version} ({project_date})"
wrap = true  # Wrap text to 79 characters
all_bullets = true  # make all fragments bullet points

  [[tool.towncrier.type]]
  directory = "added"
  name = "Added new features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "changed"
  name = "Changed existing functionality"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "deprecated"
  name = "Marked for removal"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "removed"
  name = "Removed from package"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "fixed"
  name = "Bug fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "security"
  name = "Patched vulnerabilities"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "doc"
  name = "Improved Documentation"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "trivial"
  name = "Trivial/Internal Changes"
  showcontent = true
